# Generated by Django 6.1 on 2026-08-27 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=993)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('spam_folder', models.CharField(blank=True, max_length=255)),
                ('trash_folder', models.CharField(blank=True, max_length=255)),
                ('uid_validity', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('discovering', 'discovering'), ('fetching', 'fetching'), ('classifying', 'classifying'), ('reviewing', 'reviewing'), ('applying', 'applying'), ('completed', 'completed')], default='discovering', max_length=20)),
                ('total_uids', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cleaner.account')),
            ],
        ),
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(blank=True, null=True)),
                ('message_id', models.CharField(db_index=True, max_length=998)),
                ('from_addr', models.CharField(blank=True, default='', max_length=998)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('date', models.CharField(blank=True, default='', max_length=255)),
                ('snippet', models.TextField(blank=True, default='')),
                ('ai_category', models.CharField(blank=True, choices=[('IMPORTANTE', 'IMPORTANTE'), ('SPAM', 'SPAM'), ('LIXEIRA', 'LIXEIRA')], max_length=20, null=True)),
                ('user_override', models.CharField(blank=True, choices=[('IMPORTANTE', 'IMPORTANTE'), ('SPAM', 'SPAM'), ('LIXEIRA', 'LIXEIRA')], max_length=20, null=True)),
                ('classify_status', models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=10)),
                ('apply_status', models.CharField(choices=[('not_applicable', 'not_applicable'), ('pending', 'pending'), ('applied', 'applied'), ('skipped', 'skipped'), ('failed', 'failed')], default='not_applicable', max_length=20)),
                ('apply_error', models.TextField(blank=True, default='')),
                ('batch_id', models.CharField(blank=True, default='', max_length=64)),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='cleaner.job')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'classify_status'], name='cleaner_ema_job_id_971842_idx'), models.Index(fields=['job', 'apply_status'], name='cleaner_ema_job_id_48a472_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'message_id'), name='unique_message_id_per_job')],
            },
        ),
    ]
