# Generated by Django 6.1 on 2026-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='provider',
            field=models.CharField(choices=[('custom', 'Domínio próprio'), ('gmail', 'Gmail'), ('outlook', 'Outlook')], default='custom', max_length=20),
        ),
    ]
