# Generated by Django 6.1 on 2026-08-28 20:22

from django.db import migrations, models


def rename_spam_to_span(apps, schema_editor):
    EmailRecord = apps.get_model('cleaner', 'EmailRecord')
    EmailRecord.objects.filter(ai_category='SPAM').update(ai_category='SPAN')
    EmailRecord.objects.filter(user_override='SPAM').update(user_override='SPAN')


def rename_span_to_spam(apps, schema_editor):
    EmailRecord = apps.get_model('cleaner', 'EmailRecord')
    EmailRecord.objects.filter(ai_category='SPAN').update(ai_category='SPAM')
    EmailRecord.objects.filter(user_override='SPAN').update(user_override='SPAM')


class Migration(migrations.Migration):

    dependencies = [
        ('cleaner', '0002_account_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='ai_category',
            field=models.CharField(blank=True, choices=[('IMPORTANTE', 'IMPORTANTE'), ('SPAN', 'SPAN'), ('LIXEIRA', 'LIXEIRA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='user_override',
            field=models.CharField(blank=True, choices=[('IMPORTANTE', 'IMPORTANTE'), ('SPAN', 'SPAN'), ('LIXEIRA', 'LIXEIRA')], max_length=20, null=True),
        ),
        migrations.RunPython(rename_spam_to_span, rename_span_to_spam),
    ]
