# Generated by Django 6.1 on 2026-08-28 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaner', '0003_alter_emailrecord_ai_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(db_index=True, max_length=255)),
                ('importante_count', models.IntegerField(default=0)),
                ('span_count', models.IntegerField(default=0)),
                ('lixeira_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_reputations', to='cleaner.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'sender'), name='unique_sender_per_account')],
            },
        ),
    ]
